// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ChatReq struct {
	ChatId  string `json:"chatId"`
	Message string `json:"message"`
}

type ChatResp struct {
	ChatId string      `json:"chatId"`
	Event  string      `json:"event"`
	Data   interface{} `json:"data"`
}

type UploadResp struct {
	Filename string `json:"filename"`
	Size     int64  `json:"size"`
}
