// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	chat "Echo/api/internal/handler/chat"
	file "Echo/api/internal/handler/file"
	"Echo/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/chat",
				Handler: chat.ChatHandler(serverCtx),
			},
		},
		rest.WithPrefix("/agent"),
		rest.WithSSE(),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/upload/file",
				Handler: file.UploadFileHandler(serverCtx),
			},
		},
		rest.WithPrefix("/agent"),
	)
}
